ports-wip/ruby:  bump to ruby 2.7.1.  Hit compilation error (undefined reference to 'howmany' in thread.c)  point to a japanese thread about howmany on __BEOS__ might be usefull